## Bag Of Words (BOW)
- use cases : use BOW to create count vectorizer and use them to train spam classification model

In [3]:
import pandas as pd
import numpy as np

In [1]:
cd /content/drive/MyDrive/Study/NLP/codebasics/9. Text Representation

/content/drive/MyDrive/Study/NLP/codebasics/9. Text Representation


In [5]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
df['spam'] = df.Category.apply(lambda x : 1 if x == 'spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

## Train test split

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Message'], df['spam'],test_size=0.2, random_state=40)

In [10]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(4457,) (1115,) (4457,) (1115,)


## Create bag of words representation using CountVectorizer

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X_train_cv = cv.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59518 stored elements and shape (4457, 7787)>

In [20]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
cv.get_feature_names_out()[6977]

'to'

In [15]:
dir(cv)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_r

In [16]:
cv.vocabulary_ # show vocab and its index

{'xxxmobilemovieclub': 7696,
 'to': 6977,
 'use': 7249,
 'your': 7753,
 'credit': 2085,
 'click': 1852,
 'the': 6855,
 'wap': 7414,
 'link': 4173,
 'in': 3672,
 'next': 4815,
 'txt': 7134,
 'message': 4500,
 'or': 5027,
 'here': 3445,
 'http': 3562,
 'com': 1915,
 'qjkgighjjgcbl': 5562,
 'those': 6902,
 'cocksuckers': 1893,
 'if': 3628,
 'it': 3791,
 'makes': 4367,
 'you': 7748,
 'feel': 2824,
 'better': 1347,
 'ipads': 3768,
 'are': 1055,
 'worthless': 7643,
 'garbage': 3100,
 'novelty': 4891,
 'items': 3794,
 'and': 969,
 'should': 6151,
 'bad': 1207,
 'for': 2964,
 'even': 2677,
 'wanting': 7412,
 'one': 4993,
 'now': 4893,
 'unsubscribed': 7213,
 'all': 923,
 'services': 6062,
 'get': 3144,
 'tons': 7012,
 'of': 4943,
 'sexy': 6078,
 'babes': 1197,
 'hunks': 3581,
 'straight': 6542,
 'phone': 5233,
 'go': 3189,
 'gotbabes': 3233,
 'co': 1884,
 'uk': 7160,
 'no': 4845,
 'subscriptions': 6600,
 'free': 3007,
 'entry': 2631,
 'weekly': 7476,
 'comp': 1935,
 'chance': 1734,
 'win': 755

In [19]:
# Explore how sparse X_train is
np.where(X_train_np[0] != 0)

(array([1852, 1915, 2085, 3445, 3562, 3672, 4173, 4500, 4815, 5027, 5562,
        6855, 6977, 7134, 7249, 7414, 7696, 7753]),)

In [23]:
X_train.iloc[0]

'XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL'

## Train the naive bayes model

In [24]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [31]:
X_test_cv = cv.transform(X_test)

## Evaluate performance

In [32]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.95      0.92      0.93       144

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [33]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = cv.transform(emails)
model.predict(emails_count)

array([0, 1])

## Train the model using sklearn pipeline and reduce number of lines of code

In [34]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])


In [35]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [36]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.95      0.92      0.93       144

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

